### ISSUE TITLE
user_data_dir() got an unexpected keyword argument 'ensure_exists'

### ISSUE THREAD

**Issue by Terminator98** [kaliiiiiiiiii/Selenium-Driverless#141]
I get this error when I import the library like that
``` python
from selenium_driverless.webdriver import Chrome
```

**Comment by kaliiiiiiiiii** [comment]
@Terminator98 That's the third-party `platformdirs` library.
Try `pip install --upgrade platformdirs`

**Comment by Terminator98** [comment]
> @Terminator98 That's the third-party `platformdirs` library. Try `pip install --upgrade platformdirs`

Thanks So much
I appreciate your help

**Comment by kaliiiiiiiiii** [comment]
minimum version therefore is https://github.com/platformdirs/platformdirs/pull/155

**Comment by mansh-saxena** [comment]
`
from selenium_driverless.sync import webdriver
from selenium_driverless.types.by import By
from selenium_driverless import webdriver
# import asyncio
`

Running it like this still gives me the same error. I'm new to this kind of thing so it'd be a great help if someone could figure out what the problem is. I upgraded platformdirs as well, so not sure what is going on.
