### ISSUE TITLE
Detected by DataDome Captcha

### ISSUE THREAD

**Issue by juhacz** [kaliiiiiiiiii/Selenium-Driverless#243]
Can you do something about the captcha "https://geo.captcha-delivery.com/captcha" (Datadome) appearing on the allegro.pl website?
It occurs very often, but not always, on this website, usually when I first download data from the website, when I solve the captcha, the program may run several thousand times, downloading data. When some error occurs and cron runs the script again, there is a captcha again and it happens in the middle of the night when I can fail to log.
I use Debian and Chrome.

```
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian

Chrome: Version 125.0.6422.141 (Official Build) (64-bit)
```
Of course, I also tested other versions of Chrome and the same problem occurs. Thanks for your help and again for the great piece of code.

**Comment by kaliiiiiiiiii** [comment]
This verry likely is due to your OS being suspicious & getting flagged, which driverless currently does not attempt to fix.
Or your IP getting flagged, or doing to much interaction//requests at a time.

Unless you can confirm the same occurs on Windows//MacOS whilst the IP being ok and not doing excessive requests//interactions, I wouldn't consider this as a bug.
Closing therefore for now.
